# Numpy
## Chapter 4
### Predictive Analytics for the Modern Enterprise 

This is jupyter notebook that can be used to follow along the code examples for **Chapter 4 Section 1 - Numpy** of the book.
The code examples go through some of the functionality that can be used to work with *multi-diemnsional arrays* using the Numpy library in python. 

The notebook has been tested using the following pre-requisite:

* Python V3.9.13 - https://www.python.org/
* Anaconda Navigator V3 for Python 3.9 - https://www.anaconda.com/
* Jupyter - V6.4.12 - https://jupyter.org/ 
* Desktop computer - macOS Ventura V13.1 

In [2]:
import numpy as np

### Arrays, dimensions, indexes and data types

In [4]:
np.array([0,1,2,3]) #One dimension array

array([0, 1, 2, 3])

In [6]:
np.array([[1,2,3,4], [4,3,2,1]]) #Two dimensional array 

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [26]:
threeD = np.array([[[1,2,3], [4,2,1]], [[5,6,7], [4,2,3]]]) #Three dimensional array
threeD

array([[[1, 2, 3],
        [4, 2, 1]],

       [[5, 6, 7],
        [4, 2, 3]]])

In [27]:
threeD[0,1,2]

1

In [14]:
a = np.array([1,2,3,4,5], dtype=np.float32) #Create and array of type to float
a

array([1., 2., 3., 4., 5.], dtype=float32)

### Generating Arrays

In [28]:
np.zeros((2,3)) #Two dimensional array of 0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((3,2,4)) #Three dimensional array of 1s

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [30]:
np.random.rand(2,2,3) #Three dimensional array of random numbers

array([[[0.42577929, 0.14957169, 0.4139802 ],
        [0.27451052, 0.68386878, 0.74906119]],

       [[0.91974295, 0.23597201, 0.05938353],
        [0.48170007, 0.40681348, 0.75663832]]])

In [38]:
np.arange(1,10,2) #Generate an arracy with specific sequence 

array([1, 3, 5, 7, 9])

In [39]:
np.eye(4) #Generate a 2-D array with 1 as the diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
a = np.eye(4,k=-2) #Move the diagonal up or down
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [42]:
print('Dimensions: ',  a.ndim) # Print Array dimensions

Dimensions:  2


In [43]:
print('Shape: ', a.shape) # axis(s)

Shape:  (4, 4)


In [44]:
print('Size: ', a.size) #Total Number of elements

Size:  16


### Array slicing

In [53]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) #Starting at element 0 return the 4th index item of each element
print(a[0:, 4])

[ 5 10]


In [70]:
a = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[4, 7, 2, 3, 1], [2, 5, 6, 1, 6]]]) # For all subsets, look at each of the sub-elements from 0-2 (2 excluded) and return element 4
print('Array:\n', a)
print('Element:\n', a[0:,0:2,3])

Array:
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 4  7  2  3  1]
  [ 2  5  6  1  6]]]
Element:
 [[4 9]
 [3 1]]


### Array Transformations

In [74]:
a = a = np.eye(4,k=-2)
b = np.reshape(a,(8,-1)) #-1 allows numpy to figure out the dimension
print('a:\n', a)
print('b:\n', b)

a:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
b:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]]


In [75]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) #1 dimensional array
b = a.reshape(2, 3, 2) #Reshape to 3 dimensional array
print('a:\n', a)
print('b:\n', b)


a:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
b:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [47]:
a = np.array([[1,2,3],[4,5,6]])
b = np.transpose(a) # Transpose the Array Matrix
print('Original','\n','Shape',a.shape,'\n',a)
print('Transposed:','\n','Shape',b.shape,'\n',b)

Original 
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]
Expand along columns: 
 Shape (3, 2) 
 [[1 4]
 [2 5]
 [3 6]]


### Other operations

In [91]:
a = np.array([[5,6,7,4],
              [9,2,3,7]])
print('a:\n', a)
print('Sort along column :','\n',np.sort(a, axis=1)) # sort along the column
print('Sort along row :','\n',np.sort(a, axis=0)) # sort along the row

a:
 [[5 6 7 4]
 [9 2 3 7]]
Sort along column : 
 [[4 5 6 7]
 [2 3 7 9]]
Sort along row : 
 [[5 2 3 4]
 [9 6 7 7]]


In [103]:
a = np.array([1, 2, 3, 4, 5, 4])
x = np.where(a == 5) #Find an element by value
print(x)

(array([4]),)


### Additional code samples

In [89]:
a = np.array([True, True, False, True]) #Sorting booleans
np.sort(a)
print('a:\n', a)
print('Sorted:\n', np.sort(a))

a:
 [ True  True False  True]
Sorted:
 [False  True  True  True]


In [88]:
a = np.array(['Karachi','Dubai','New York']) #Sorting strings 
np.sort(a)
print('a:\n', a)
print('Sorted:\n', np.sort(a))

a:
 ['Karachi' 'Dubai' 'New York']
Sorted:
 ['Dubai' 'Karachi' 'New York']


In [95]:
a = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(a < 4) #Find an element by comparison
print(x)

(array([0, 1, 2]),)


In [104]:
arr = np.array([10, 12, 14, 20])
x = np.searchsorted(arr, 15) # Find the index where 15 should be inserted
print(x)

3


In [78]:
a = a = np.eye(4)
b = a.flatten() # Flattens the array and Returns a copy of the original array
print('a:\n', a)
print('b:\n', b)

a:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
b:
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


In [79]:
b[0] = 3
print(a) #a is unchanged when b is updated

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [80]:
b = a.ravel() #Flattens but maintains a link to the original array
print('a:\n', a)
print('b:\n', b)

a:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
b:
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


In [81]:
b[0] = 3
print(a) #a gets changed when b is updated

[[3. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [92]:
a = np.array(["A","C","B","X"])
b = np.expand_dims(a,axis=0) #increase dimension on axis 0
c = np.expand_dims(a,axis=1) #increase dimension on axis 1
print('a:\n', a)
print('b:\n', b)
print('c:\n', c)

a:
 ['A' 'C' 'B' 'X']
b:
 [['A' 'C' 'B' 'X']]
c:
 [['A']
 ['C']
 ['B']
 ['X']]


In [4]:
a = np.array([[[1,2,3],[4,5,6]]])
b = np.squeeze(a, axis=0) #Reduce dimension on axis 0
print('a:\n', a)
print('b:\n', b)


[[[1 2 3]
  [4 5 6]]]
[[1 2 3]
 [4 5 6]]


In [3]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('a :','\n',a)
print('Vertical Flip :','\n',np.flip(a,axis=1)) # Flips on vertical axis
print('Horizontal Flip :','\n',np.flip(a,axis=0)) # Flips on horizontal axis

a : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Vertical Flip : 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]
Horizontal Flip : 
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [4]:
a = np.arange(0,5)
b = np.arange(5,10)
print('a :','\n',a)
print('b :','\n',b)
print('Vertical stack :','\n',np.vstack((a,b))) # Stack vertically
print('Horizontal stack :','\n',np.hstack((a,b))) #Stack horizontally

a : 
 [0 1 2 3 4]
b : 
 [5 6 7 8 9]
Vertical stack : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Horizontal stack : 
 [0 1 2 3 4 5 6 7 8 9]


In [108]:
a = np.arange(10,20,2)
b = np.array([[2],[5]])
print('a :',a)
print('Adding two different size arrays :','\n',a+b) #Adding Arrays
print('Multiplying an ndarray and a number :',a*2) #Multiplying an array with a scalar

a : 
 [10 12 14 16 18]
Adding two different size arrays : 
 [[12 14 16 18 20]
 [15 17 19 21 23]]
Multiplying an ndarray and a number : [20 24 28 32 36]


In [110]:
print('a :',a)
print('Subtract :',a-2)
print('Multiply :',a*10)
print('Divide :',a/50)
print('Power :',a**4)
print('Remainder :',a%3)

a : [10 12 14 16 18]
Subtract : [ 8 10 12 14 16]
Multiply : [100 120 140 160 180]
Divide : [0.2  0.24 0.28 0.32 0.36]
Power : [ 10000  20736  38416  65536 104976]
Remainder : [1 0 2 1 0]


In [111]:
a = np.arange(5,15,2)
print('a :',a)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

a : [ 5  7  9 11 13]
Mean : 9.0
Standard deviation : 2.8284271247461903
Median : 9.0


In [114]:
a = np.array([[1,6],[4,3]])
print('a :\n',a)
print('Min - column:',np.min(a,axis=0)) # minimum along a column
print('Max - row:',np.max(a,axis=1)) # maximum along a row

a :
 [[1 6]
 [4 3]]
Min - column: [1 3]
Max - row: [6 4]


In [115]:
a = np.array([[1,6,5],[4,3,7]])
print('Min :',np.argmin(a,axis=0)) #Index of min along cloumn
print('Max :',np.argmax(a,axis=1)) #Index of max along row

Min : [0 1 0]
Max : [1 2]
