# Numpy
## Chapter 5
### Predictive Analytics for the Modern Enterprise 

This is jupyter notebook that can be used to follow along the code examples for **Chapter 5 Section 1 - Numpy** of the book.
The code examples go through some of the functionality that can be used to work with *multi-diemnsional arrays* using the Numpy library in python. 

The notebook has been tested using the following pre-requisite:

* Python V3.9.13 - https://www.python.org/
* Anaconda Navigator V3 for Python 3.9 - https://www.anaconda.com/
* Jupyter - V6.4.12 - https://jupyter.org/ 
* Desktop computer - macOS Ventura V13.1 

### Installation

In case you don't have numpy installed use the following command to install numpy in your environment

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

### Arrays, dimensions, indexes and data types

In [2]:
np.array([0,1,2,3]) #One dimension array

array([0, 1, 2, 3])

In [3]:
np.array([[1,2,3,4], [4,3,2,1]]) #Two dimensional array 

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [4]:
threeD = np.array([[[1,2,3], [4,2,1]], [[5,6,7], [4,2,3]]]) #Three dimensional array
threeD

array([[[1, 2, 3],
        [4, 2, 1]],

       [[5, 6, 7],
        [4, 2, 3]]])

In [5]:
threeD[0,1,2]

1

In [6]:
a = np.array([1,2,3,4,5], dtype=np.float32) #Create and array of type to float
a

array([1., 2., 3., 4., 5.], dtype=float32)

### Generating Arrays

In [7]:
np.zeros((2,3)) #Two dimensional array of 0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((3,2,4)) #Three dimensional array of 1s

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [9]:
np.random.rand(2,2,3) #Three dimensional array of random numbers

array([[[0.95730157, 0.51635363, 0.50917556],
        [0.4544881 , 0.59785864, 0.02349391]],

       [[0.61578269, 0.86567812, 0.13580105],
        [0.32494046, 0.36011782, 0.07138273]]])

In [10]:
np.arange(1,10,2) #Generate an arracy with specific sequence 

array([1, 3, 5, 7, 9])

In [11]:
np.eye(4) #Generate a 2-D array with 1 as the diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
a = np.eye(4,k=-2) #Move the diagonal up or down
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [13]:
print('Dimensions: ',  a.ndim) # Print Array dimensions

Dimensions:  2


In [14]:
print('Shape: ', a.shape) # axis(s)

Shape:  (4, 4)


In [15]:
print('Size: ', a.size) #Total Number of elements

Size:  16


### Array slicing

In [16]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) #Starting at element 0 return the 4th index item of each element
print(a[0:, 4])

[ 5 10]


In [17]:
a = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[4, 7, 2, 3, 1], [2, 5, 6, 1, 6]]]) # For all subsets, look at each of the sub-elements from 0-2 (2 excluded) and return element 4
print('Array:\n', a)
print('Element:\n', a[0:,0:2,3])

Array:
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 4  7  2  3  1]
  [ 2  5  6  1  6]]]
Element:
 [[4 9]
 [3 1]]


### Array Transformations

In [19]:
a = a = np.eye(4,k=-2)
b = np.reshape(a,(8,-1)) #-1 allows numpy to figure out the dimension
print('a:\n', a)
print('b:\n', b)

a:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
b:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]]


In [20]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) #1 dimensional array
b = a.reshape(2, 3, 2) #Reshape to 3 dimensional array
print('a:\n', a)
print('b:\n', b)


a:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
b:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [21]:
a = np.array([[1,2,3],[4,5,6]])
b = np.transpose(a) # Transpose the Array Matrix
print('Original','\n','Shape',a.shape,'\n',a)
print('Transposed:','\n','Shape',b.shape,'\n',b)

Original 
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]
Transposed: 
 Shape (3, 2) 
 [[1 4]
 [2 5]
 [3 6]]


### Other operations

In [22]:
a = np.array([[5,6,7,4],
              [9,2,3,7]])
print('a:\n', a)
print('Sort along column :','\n',np.sort(a, axis=1)) # sort along the column
print('Sort along row :','\n',np.sort(a, axis=0)) # sort along the row

a:
 [[5 6 7 4]
 [9 2 3 7]]
Sort along column : 
 [[4 5 6 7]
 [2 3 7 9]]
Sort along row : 
 [[5 2 3 4]
 [9 6 7 7]]


In [23]:
a = np.array([1, 2, 3, 4, 5, 4])
x = np.where(a == 5) #Find an element by value
print(x)

(array([4]),)


### Cinema Example

In [8]:
# Define dimensions
months = 12

# Create a 1D array with dimensions (months) We have just 1 cinema and 1 category
# We are using a random function to generate ticket sales values between 80 - 1200
ticket_sales = np.random.randint(80, 1201, size=(months))

print("1D Array Shape:", ticket_sales.shape)
print("Sample Data:")
ticket_sales

1D Array Shape: (12,)
Sample Data:


array([ 233,  725,  356,  501,  412,  125, 1062,  106, 1067,  103,  119,
       1070])

In [9]:
# Define dimensions
months = 12
categories = 3

# Create a 2D array with dimensions (months, categories) we just have 1 cinema
# We are using a random function to generate ticket sales values between 80 - 1200
ticket_sales = np.random.randint(80, 1201, size=(months, categories))

print("2D Array Shape:", ticket_sales.shape)
print("Sample Data:")
ticket_sales

2D Array Shape: (12, 3)
Sample Data:


array([[  81,  344,  869],
       [ 448,  546,  726],
       [ 598,  545,  797],
       [ 443,  966, 1040],
       [ 645,  293,  569],
       [ 253,  672,  911],
       [ 719,  629, 1193],
       [ 967,  839, 1131],
       [ 892, 1101,  340],
       [ 854,  491,  552],
       [ 536,  207,  210],
       [ 174, 1081,  404]])

In [13]:
# Define dimensions
months = 12
categories = 3
cinemas = 9

# Create a 3D array with dimensions (months, categories, cinemas)
# We are using a random function to generate ticket sales values between 80 - 1200
ticket_sales = np.random.randint(80, 1201, size=(cinemas, months, categories))

print("3D Array Shape:", ticket_sales.shape)
print("Sample Data:")
ticket_sales

3D Array Shape: (9, 12, 3)
Sample Data:


array([[[ 838, 1039,  611],
        [1022,  492,  504],
        [ 256,  645,  706],
        [ 759,  681,  612],
        [ 887, 1159,  483],
        [ 724,  243,  666],
        [ 778, 1005,  783],
        [ 675,  941,  772],
        [ 481,  198,  932],
        [ 233,  935,  905],
        [ 365,  233,  385],
        [ 244,  386,  409]],

       [[ 995,  111,  978],
        [ 511,  650,  582],
        [ 972,  378,  168],
        [ 425,  319,  873],
        [ 984,  183, 1144],
        [ 805,  345,   81],
        [ 210,  950,  161],
        [ 177,  191,  590],
        [ 708,  449,  766],
        [ 257, 1138,  139],
        [1037,  241,  770],
        [ 609,  213,  439]],

       [[ 225,  204,  943],
        [  81,  535,  373],
        [ 245,  315, 1122],
        [1118,  350,  782],
        [ 687,  829,  792],
        [1037,  920,  131],
        [ 686,  152,  183],
        [ 699,  363,  564],
        [ 952,  597,  227],
        [1166,  681,  335],
        [ 272,  485, 1094],
        [ 337,  

Let us try and answer the questions we discussed earlier

Q1: What is the total number of tickets sold across all cinemas in a month

In [21]:
# Sum the ticket sales across all cinemas for each month
total_tickets_per_month = np.sum(ticket_sales, axis=(0, 2))

# Print the total number of tickets sold across all cinemas in each month
for month, total_tickets in enumerate(total_tickets_per_month):
    print(f"Month {month}: Total tickets sold = {total_tickets}")

Month 0: Total tickets sold = 17958
Month 1: Total tickets sold = 14514
Month 2: Total tickets sold = 14355
Month 3: Total tickets sold = 16345
Month 4: Total tickets sold = 18627
Month 5: Total tickets sold = 17443
Month 6: Total tickets sold = 14885
Month 7: Total tickets sold = 17202
Month 8: Total tickets sold = 14455
Month 9: Total tickets sold = 18962
Month 10: Total tickets sold = 15764
Month 11: Total tickets sold = 18636


Q2: How do the sales of Regular tickets in Cinema 1 compare to Cinema 7 in the month of June?

In [19]:
june_sales_cinema1_regular = ticket_sales[1, 5, 0] #(Cinema 1, June = 5 (as January = 0), Regular Category = 0)
june_sales_cinema7_regular = ticket_sales[7, 5, 0] #(Cinema 7, June = 5 (as January = 0), Regular Category = 0)
print("June Sales for Regular Tickets")
print("Cinema 1: ", june_sales_cinema1_regular)
print("Cinema 7: ", june_sales_cinema7_regular)

June Sales for Regular Tickets
Cinema 1:  805
Cinema 7:  908


### Additional code samples

In [24]:
a = np.array([True, True, False, True]) #Sorting booleans
np.sort(a)
print('a:\n', a)
print('Sorted:\n', np.sort(a))

a:
 [ True  True False  True]
Sorted:
 [False  True  True  True]


In [25]:
a = np.array(['Karachi','Dubai','New York']) #Sorting strings 
np.sort(a)
print('a:\n', a)
print('Sorted:\n', np.sort(a))

a:
 ['Karachi' 'Dubai' 'New York']
Sorted:
 ['Dubai' 'Karachi' 'New York']


In [27]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr < 4) #Find an element by comparison
print(x)

(array([0, 1, 2]),)


In [28]:
arr = np.array([10, 12, 14, 20])
x = np.searchsorted(arr, 15) # Find the index where 15 should be inserted
print(x)

3


In [29]:
a = a = np.eye(4)
b = a.flatten() # Flattens the array and Returns a copy of the original array
print('a:\n', a)
print('b:\n', b)

a:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
b:
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


In [30]:
b[0] = 3
print(a) #a is unchanged when b is updated

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
b = a.ravel() #Flattens but maintains a link to the original array
print('a:\n', a)
print('b:\n', b)

a:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
b:
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


In [32]:
b[0] = 3
print(a) #a gets changed when b is updated

[[3. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
a = np.array(["A","C","B","X"])
b = np.expand_dims(a,axis=0) #increase dimension on axis 0
c = np.expand_dims(a,axis=1) #increase dimension on axis 1
print('a:\n', a)
print('b:\n', b)
print('c:\n', c)

a:
 ['A' 'C' 'B' 'X']
b:
 [['A' 'C' 'B' 'X']]
c:
 [['A']
 ['C']
 ['B']
 ['X']]


In [34]:
a = np.array([[[1,2,3],[4,5,6]]])
b = np.squeeze(a, axis=0) #Reduce dimension on axis 0
print('a:\n', a)
print('b:\n', b)


a:
 [[[1 2 3]
  [4 5 6]]]
b:
 [[1 2 3]
 [4 5 6]]


In [35]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('a :','\n',a)
print('Vertical Flip :','\n',np.flip(a,axis=1)) # Flips on vertical axis
print('Horizontal Flip :','\n',np.flip(a,axis=0)) # Flips on horizontal axis

a : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Vertical Flip : 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]
Horizontal Flip : 
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [36]:
a = np.arange(0,5)
b = np.arange(5,10)
print('a :','\n',a)
print('b :','\n',b)
print('Vertical stack :','\n',np.vstack((a,b))) # Stack vertically
print('Horizontal stack :','\n',np.hstack((a,b))) #Stack horizontally

a : 
 [0 1 2 3 4]
b : 
 [5 6 7 8 9]
Vertical stack : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Horizontal stack : 
 [0 1 2 3 4 5 6 7 8 9]


In [37]:
a = np.arange(10,20,2)
b = np.array([[2],[5]])
print('a :',a)
print('Adding two different size arrays :','\n',a+b) #Adding Arrays
print('Multiplying an ndarray and a number :',a*2) #Multiplying an array with a scalar

a : [10 12 14 16 18]
Adding two different size arrays : 
 [[12 14 16 18 20]
 [15 17 19 21 23]]
Multiplying an ndarray and a number : [20 24 28 32 36]


In [38]:
print('a :',a)
print('Subtract :',a-2)
print('Multiply :',a*10)
print('Divide :',a/50)
print('Power :',a**4)
print('Remainder :',a%3)

a : [10 12 14 16 18]
Subtract : [ 8 10 12 14 16]
Multiply : [100 120 140 160 180]
Divide : [0.2  0.24 0.28 0.32 0.36]
Power : [ 10000  20736  38416  65536 104976]
Remainder : [1 0 2 1 0]


In [39]:
a = np.arange(5,15,2)
print('a :',a)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

a : [ 5  7  9 11 13]
Mean : 9.0
Standard deviation : 2.8284271247461903
Median : 9.0


In [40]:
a = np.array([[1,6],[4,3]])
print('a :\n',a)
print('Min - column:',np.min(a,axis=0)) # minimum along a column
print('Max - row:',np.max(a,axis=1)) # maximum along a row

a :
 [[1 6]
 [4 3]]
Min - column: [1 3]
Max - row: [6 4]


In [41]:
a = np.array([[1,6,5],[4,3,7]])
print('Min :',np.argmin(a,axis=0)) #Index of min along cloumn
print('Max :',np.argmax(a,axis=1)) #Index of max along row

Min : [0 1 0]
Max : [1 2]
